### ISSUE TITLE
Why not use transformers?

### ISSUE THREAD

**Issue by zxti** [generalpiston/typeorm-encrypted#14]
Why does this library use subscribers rather than plain transformers in typeorm? Was it because this came out before transformers were introduced into typeorm?

**Comment by generalpiston** [comment]
@zxti I wrote this library a while ago. I don't recall transformers. Do you have documentation?

**Comment by generalpiston** [comment]
Seems like a 2017 novelty: https://typeorm.io/#/entities/column-options
