### ISSUE TITLE
generate key "Invalid key length"

### ISSUE THREAD

**Issue by Paul75** [generalpiston/typeorm-encrypted#23]
Hello,

When I generate key I see error : "Invalid key length"

I do for exemple : 
```
export const MyEncryptionTransformerConfig = {
    key: Buffer.from(env.app.crypto.key, 'utf8').toString('base64'),
    algorithm: env.app.crypto.algorithm,
    ivLength: 16,
};
```
In env I add : 
`env.app.crypto.key = nCM*R$izc*G3vqg7jo086mbc9Rg^7NYl
`

Thanks

**Comment by Paul75** [comment]
Helllo,

Ok I see thant must generate key like : 

 ```
const Crypto = require('crypto');
            return Crypto.randomBytes(size)
                .toString('hex')
                ;
```

Thanks

**Comment by generalpiston** [comment]
@Paul75 there are a lot of ways to generate keys...
- https://www.openssl.org/docs/man1.0.2/man1/openssl-rand.html
- https://stackoverflow.com/questions/40277918/shell-script-to-generate-random-hex-numbers
