### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ontimond** [generalpiston/typeorm-encrypted#29]
I currently have a problem when I run the npm run start, I'm not quite sure if it's a problem with the typescript setting

`error TS2307: Cannot find module 'typeorm-encrypted' or its corresponding type declarations.`

`tsconfig.json`

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}                                            
```

**Comment by generalpiston** [comment]
1. Try deleting your `node_modules` directory and running `npm i` again.
2. Try disabling incremental compilation.
3. Try adding `"lib": ["es5", "es6", "esnext.asynciterable"]`.

**Comment by ontimond** [comment]
Thanks, it worked deleting the node_modules folder
