### ISSUE TITLE
Can i do a filter operation or serch operation using this

### ISSUE THREAD

**Issue by viraniparth00001** [generalpiston/typeorm-encrypted#33]
Hello ,

i have database requirement is fully encrypted database to store i also requirement to filter all record so can it is possible to do a search operation  with encrypted database using typeorm?

if it is really possible so give your throat how we have do it ?

**Comment by generalpiston** [comment]
@viraniparth00001 typeorm-encryped is a library for encrypting specific fields. To encrypt your database, you'll have to consult the manual for that database. Popular relation databases like MySQL and PostgreSQL support data-at-rest and in-flight encryption IIRC. Typeorm would only need the credentials to connect to the DB.

This is, however, a common question. I've created https://github.com/generalpiston/typeorm-encrypted/issues/34 to follow-up on adding a better answer in our README.
