### ISSUE TITLE
Invalid IV length

### ISSUE THREAD

**Issue by ecorrales1979** [generalpiston/typeorm-encrypted#35]
I was trying to reproduce your examples using column transformer (just copy/paste your code) and got the error: Invalid IV length

I was able to create a new entity, but when I tried to get the data, I got that error. Any hint about this, please?

**Comment by generalpiston** [comment]
@ecorrales1979 can you provide your configuration? Also, are you adding the library on top of an existing data set?

**Comment by ecorrales1979** [comment]
It's working. I just cleaned the typeorm cache and it worked like a charm.
Thanks

**Comment by generalpiston** [comment]
@ecorrales1979 query cache? We should add that to the docs.

**Comment by ecorrales1979** [comment]
Yes, the query runner cache. I don't know if others will have this problem, but for me it worked.
Thanks
