### ISSUE TITLE
Support for typeorm 0.3

### ISSUE THREAD

**Issue by tjhiggins** [generalpiston/typeorm-encrypted#55]
https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md

**Comment by tjhiggins** [comment]
please update the peer dep to support ^0.3.0
https://github.com/generalpiston/typeorm-encrypted/blob/master/package.json#L21

**Comment by generalpiston** [comment]
@tjhiggins sure. We'll need to check if typeorm 0.3.0 have any breaking changes.

**Comment by tjhiggins** [comment]
@generalpiston thank you!

**Comment by bhaugeea** [comment]
Any update on this?

**Comment by pedronfigueiredo** [comment]
@generalpiston are you accepting PRs on this?

**Comment by generalpiston** [comment]
@pedronfigueiredo absolutely!

**Comment by pedronfigueiredo** [comment]
Opened https://github.com/generalpiston/typeorm-encrypted/pull/57, have a look!

**Comment by generalpiston** [comment]
Merged and released. Thank you @pedronfigueiredo :).
