### ISSUE TITLE
[Question] How is key rotation handled?

### ISSUE THREAD

**Issue by bombillazo** [generalpiston/typeorm-encrypted#60]
Hey, if one is using key rotation for improved security, how does that affect the use of this package?

**Comment by bombillazo** [comment]
After reading more on the topic seems like this is the common approach! Thanks for answering!

**Comment by generalpiston** [comment]
No problem.

Let's use https://github.com/generalpiston/typeorm-encrypted/issues/61 to document how to handle key rotation.

**Comment by texiontech** [comment]
any update

**Comment by generalpiston** [comment]
@texiontech the key rotation issue is tracked under https://github.com/generalpiston/typeorm-encrypted/issues/61

**Comment by oscarnc** [comment]
I ended up doing something like this:
```
const createTransformer = (key) => new EncryptionTransformer({
  key,
  algorithm: 'aes-256-gcm',
  ivLength: 16,
});
const oldTransformer = createTransformer('oldKey');
const newTransformer = createTransformer('newKey');
const repo = getRepository(User);
const col = repo.metadata.findColumnWithPropertyName('secret');
col.transformer = {
  from: (dbValue) => oldTransformer.from(dbValue),
  to: (entityValue) => newTransformer.to(entityValue),
};
const users = await repo.find();
await repo.save(users);
```

**Comment by generalpiston** [comment]
Thanks @oscarnc .
