### ISSUE TITLE
conditionally encryption columns

### ISSUE THREAD

**Issue by basz** [generalpiston/typeorm-encrypted#70]
I would like a way to conditionally encrypt columns

specifically I have a key value table (used to store in this case some sort of preferences). Dependant on the value of the key the value colums should or shouldn't be encrypted.

I image that a callback with the entity as argument could be added to the options that enables or disabled the encryption without much trouble?

Would such a feature be appreciated?

```
encrypt: {
      key: "d85117047fd06d3afa79b6e44ee3a52eb426fc24c3a2e3667732e8da0342b4da",
      algorithm: "aes-256-gcm",
      ivLength: 16,
      enabled: (entity: MyEntity) => entity.key === 'apiKey',
    }
```

**Comment by generalpiston** [comment]
@basz seems super useful. Encryption happens client-side, so it makes sense.

**Comment by basz** [comment]
sure, it will be fun... just gove me a few days as I'm swamped atm

**Comment by basz** [comment]
> Encryption happens client-side, so it makes sense.

What do you mean by that remark? Seems your have two distinct conditions for encryption and decryption.
